Myaccount
linhvth/good-meals pull request #16
Opened 2023-05-24 09:40 UTC by imkhoibui

2023-05-24 10:32 UTC, linhvth requested changes
Hi @imkhoibui , please review the Recipe.js file and modify it as requested. Thank you, and nice try.

2023-05-24 10:32 UTC, linhvth commented on src/components/Recipe.js
@imkhoibui 
This file lacks functionalities. You completed handling the click event pretty well. However, you have not yet handled the bookmark status of each recipe for each user. It seems like whoever and whenever go to a particular recipe page, the bookmark is always marked.

2023-05-24 13:18 UTC, imkhoibui commented
Hi, I fixed the code and tested okay for myself. Hope you can recheck it for me, thanks!

2023-05-25 00:35 UTC, linhvth approved these changes

2023-05-25 00:35 UTC, merged